import {
  getEngineBoundarySummary,
  type EngineBoundarySummary,
} from "../internal/foundation";
import {
  inferAverageTrueRange,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
} from "../internal/model";
import type {
  PhaseOneMainChartType,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
} from "../internal/model";
import {
  createPhaseOneChart,
  mountPhaseOneChartHarness,
  type PhaseOneAreaSeriesApi,
  type PhaseOneAreaSeriesOptions,
  type PhaseOneBaselineSeriesApi,
  type PhaseOneBaselineSeriesOptions,
  type PhaseOneBarSeriesOptions,
  type PhaseOneBarSeriesApi,
  type PhaseOneCandlestickData,
  type PhaseOneCandlestickSeriesApi,
  type PhaseOneCandlestickSeriesOptions,
  type PhaseOneChartApi,
  type PhaseOneChartOptions,
  type PhaseOneChartStateSnapshot,
  type PhaseOneChartTemplate,
  type PhaseOneChartTemplateInput,
  type PhaseOneCompareSeriesOptions,
  type PhaseOneCompareSeriesApi,
  type PhaseOneDrawingPropertyField,
  type PhaseOneDrawingPropertyFieldSchema,
  type PhaseOneDrawingPropertySchema,
  type PhaseOneDrawingPropertySectionSchema,
  type PhaseOneDrawingSelectionChangeHandler,
  type PhaseOneDrawingStateSnapshot,
  type PhaseOneClickEvent,
  type PhaseOneClickHandler,
  type PhaseOneCrosshairMoveEvent,
  type PhaseOneCrosshairMoveHandler,
  type PhaseOneHistogramData,
  type PhaseOneHistogramSeriesApi,
  type PhaseOneHistogramSeriesOptions,
  type PhaseOneHorizontalLineDrawingApi,
  type PhaseOneHorizontalLineDrawingOptions,
  type PhaseOneLineData,
  type PhaseOneLineSeriesApi,
  type PhaseOneLineSeriesOptions,
  type PhaseOneMainSeriesApi,
  type PhaseOneMainSeriesStateSnapshot,
  type PhaseOneMovingAverageStudyApi,
  type PhaseOneMovingAverageStudyOptions,
  type PhaseOneOverlaySeriesApi,
  type PhaseOnePaneApi,
  type PhaseOnePaneEvent,
  type PhaseOnePaneEventHandler,
  type PhaseOnePaneEventType,
  type PhaseOnePaneKind,
  type PhaseOnePaneOptions,
  type PhaseOnePaneSeriesState,
  type PhaseOnePaneState,
  type PhaseOnePaneResizeEvent,
  type PhaseOnePaneResizeHandler,
  type PhaseOnePriceLineApi,
  type PhaseOnePriceLineOptions,
  type PhaseOnePriceScaleApi,
  type PhaseOneFormattedReadoutValues,
  type PhaseOneReadoutDetail,
  type PhaseOneReadoutSeriesDetail,
  type PhaseOneSelectedDrawing,
  type PhaseOneSeriesMarker,
  type PhaseOneSeriesMarkerPosition,
  type PhaseOneSeriesMarkerShape,
  type PhaseOneSeriesTarget,
  type PhaseOneSeriesValueFormatter,
  type PhaseOneTimeScaleApi,
  type PhaseOneChartTypeChangeHandler,
  type PhaseOneTrendLineDrawingApi,
  type PhaseOneTrendLineDrawingOptions,
  type PhaseOneVolumeData,
  type PhaseOneVolumeSeriesApi,
  type PhaseOneVolumeSeriesOptions,
  type PhaseOneVolumeSeriesTarget,
} from "../internal/views";
import {
  createPerformanceReportModel,
  createSampleStrategyRun,
  createTradeLocationIntent,
  type AxisModel,
  type BenchmarkSeries,
  type BreakdownDataset,
  type BreakdownSlice,
  type BreakdownSpec,
  type ClosedTrade,
  type DistributionBin,
  type DistributionDataset,
  type DistributionSpec,
  type EquityBasis,
  type EquitySeries,
  type EquitySeriesPoint,
  type EquitySeriesSpec,
  type EquitySnapshot,
  type FillEvent,
  type MeasureUnit,
  type MetricCardModel,
  type NormalizationMode,
  type NumericScaleModel,
  type OrderEvent,
  type OrderSide,
  type OrderType,
  type PerformanceMetricKey,
  type PerformanceReportSnapshot,
  type PerformanceReportView,
  type PerformanceScope,
  type PerformanceVisualKind,
  type SideSlice,
  type StrategyRunModel,
  type TradeListRow,
  type TradeLocationIntent,
  type TradeSide,
  type XDomainKind,
} from "../internal/performance";

export type {
  EngineBoundarySummary,
  PhaseOneAreaSeriesApi,
  PhaseOneAreaSeriesOptions,
  PhaseOneBaselineSeriesApi,
  PhaseOneBaselineSeriesOptions,
  PhaseOneBarSeriesOptions,
  PhaseOneBarSeriesApi,
  PhaseOneCandlestickData,
  PhaseOneCandlestickSeriesApi,
  PhaseOneCandlestickSeriesOptions,
  PhaseOneChartApi,
  PhaseOneChartOptions,
  PhaseOneChartStateSnapshot,
  PhaseOneChartTemplate,
  PhaseOneChartTemplateInput,
  PhaseOneCompareSeriesOptions,
  PhaseOneCompareSeriesApi,
  PhaseOneDrawingPropertyField,
  PhaseOneDrawingPropertyFieldSchema,
  PhaseOneDrawingPropertySchema,
  PhaseOneDrawingPropertySectionSchema,
  PhaseOneDrawingSelectionChangeHandler,
  PhaseOneDrawingStateSnapshot,
  PhaseOneClickEvent,
  PhaseOneClickHandler,
  PhaseOneCrosshairMoveEvent,
  PhaseOneCrosshairMoveHandler,
  PhaseOneHistogramData,
  PhaseOneHistogramSeriesApi,
  PhaseOneHistogramSeriesOptions,
  PhaseOneHorizontalLineDrawingApi,
  PhaseOneHorizontalLineDrawingOptions,
  PhaseOneLineData,
  PhaseOneLineSeriesApi,
  PhaseOneLineSeriesOptions,
  PhaseOneMainChartType,
  PhaseOneMainSeriesApi,
  PhaseOneMainSeriesStateSnapshot,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneMovingAverageStudyApi,
  PhaseOneMovingAverageStudyOptions,
  PhaseOneOverlaySeriesApi,
  PhaseOnePaneApi,
  PhaseOnePaneEvent,
  PhaseOnePaneEventHandler,
  PhaseOnePaneEventType,
  PhaseOnePaneKind,
  PhaseOnePaneOptions,
  PhaseOnePaneSeriesState,
  PhaseOnePaneState,
  PhaseOnePaneResizeEvent,
  PhaseOnePaneResizeHandler,
  PhaseOnePriceLineApi,
  PhaseOnePriceLineOptions,
  PhaseOnePriceScaleApi,
  PhaseOneFormattedReadoutValues,
  PhaseOneReadoutDetail,
  PhaseOneReadoutSeriesDetail,
  PhaseOneSelectedDrawing,
  PhaseOneSeriesMarker,
  PhaseOneSeriesMarkerPosition,
  PhaseOneSeriesMarkerShape,
  PhaseOneSeriesTarget,
  PhaseOneSeriesValueFormatter,
  PhaseOneTimeScaleApi,
  PhaseOneChartTypeChangeHandler,
  PhaseOneTrendLineDrawingApi,
  PhaseOneTrendLineDrawingOptions,
  PhaseOneVolumeData,
  PhaseOneVolumeSeriesApi,
  PhaseOneVolumeSeriesOptions,
  PhaseOneVolumeSeriesTarget,
  AxisModel,
  BenchmarkSeries,
  BreakdownDataset,
  BreakdownSlice,
  BreakdownSpec,
  ClosedTrade,
  DistributionBin,
  DistributionDataset,
  DistributionSpec,
  EquityBasis,
  EquitySeries,
  EquitySeriesPoint,
  EquitySeriesSpec,
  EquitySnapshot,
  FillEvent,
  MeasureUnit,
  MetricCardModel,
  NormalizationMode,
  NumericScaleModel,
  OrderEvent,
  OrderSide,
  OrderType,
  PerformanceMetricKey,
  PerformanceReportSnapshot,
  PerformanceReportView,
  PerformanceScope,
  PerformanceVisualKind,
  SideSlice,
  StrategyRunModel,
  TradeListRow,
  TradeLocationIntent,
  TradeSide,
  XDomainKind,
};

export function getChartxFoundation(): EngineBoundarySummary {
  return getEngineBoundarySummary();
}

export function mountChartxPhaseOneHarness(canvas: HTMLCanvasElement): () => void {
  return mountPhaseOneChartHarness(canvas);
}

export function createChartxPhaseOneChart(canvas: HTMLCanvasElement): PhaseOneChartApi {
  return createPhaseOneChart(canvas);
}

export {
  createPerformanceReportModel,
  createSampleStrategyRun,
  createTradeLocationIntent,
  inferAverageTrueRange,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
};
