import {
  getEngineBoundarySummary,
  type EngineBoundarySummary,
} from "../internal/foundation";
import type {
  PhaseOneMainChartType,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
} from "../internal/model";
import {
  createPhaseOneChart,
  mountPhaseOneChartHarness,
  type PhaseOneAreaSeriesApi,
  type PhaseOneAreaSeriesOptions,
  type PhaseOneBaselineSeriesApi,
  type PhaseOneBaselineSeriesOptions,
  type PhaseOneBarSeriesOptions,
  type PhaseOneBarSeriesApi,
  type PhaseOneCandlestickData,
  type PhaseOneCandlestickSeriesApi,
  type PhaseOneCandlestickSeriesOptions,
  type PhaseOneChartApi,
  type PhaseOneChartOptions,
  type PhaseOneCompareSeriesOptions,
  type PhaseOneCompareSeriesApi,
  type PhaseOneClickEvent,
  type PhaseOneClickHandler,
  type PhaseOneCrosshairMoveEvent,
  type PhaseOneCrosshairMoveHandler,
  type PhaseOneHistogramData,
  type PhaseOneHistogramSeriesApi,
  type PhaseOneHistogramSeriesOptions,
  type PhaseOneLineData,
  type PhaseOneLineSeriesApi,
  type PhaseOneLineSeriesOptions,
  type PhaseOneMainSeriesApi,
  type PhaseOneMovingAverageStudyApi,
  type PhaseOneMovingAverageStudyOptions,
  type PhaseOneOverlaySeriesApi,
  type PhaseOnePaneApi,
  type PhaseOnePaneEvent,
  type PhaseOnePaneEventHandler,
  type PhaseOnePaneEventType,
  type PhaseOnePaneKind,
  type PhaseOnePaneOptions,
  type PhaseOnePaneSeriesState,
  type PhaseOnePaneState,
  type PhaseOnePaneResizeEvent,
  type PhaseOnePaneResizeHandler,
  type PhaseOnePriceLineApi,
  type PhaseOnePriceLineOptions,
  type PhaseOnePriceScaleApi,
  type PhaseOneReadoutDetail,
  type PhaseOneReadoutSeriesDetail,
  type PhaseOneSeriesMarker,
  type PhaseOneSeriesMarkerPosition,
  type PhaseOneSeriesMarkerShape,
  type PhaseOneSeriesTarget,
  type PhaseOneTimeScaleApi,
  type PhaseOneChartTypeChangeHandler,
  type PhaseOneVolumeData,
  type PhaseOneVolumeSeriesApi,
  type PhaseOneVolumeSeriesOptions,
  type PhaseOneVolumeSeriesTarget,
} from "../internal/views";

export type {
  EngineBoundarySummary,
  PhaseOneAreaSeriesApi,
  PhaseOneAreaSeriesOptions,
  PhaseOneBaselineSeriesApi,
  PhaseOneBaselineSeriesOptions,
  PhaseOneBarSeriesOptions,
  PhaseOneBarSeriesApi,
  PhaseOneCandlestickData,
  PhaseOneCandlestickSeriesApi,
  PhaseOneCandlestickSeriesOptions,
  PhaseOneChartApi,
  PhaseOneChartOptions,
  PhaseOneCompareSeriesOptions,
  PhaseOneCompareSeriesApi,
  PhaseOneClickEvent,
  PhaseOneClickHandler,
  PhaseOneCrosshairMoveEvent,
  PhaseOneCrosshairMoveHandler,
  PhaseOneHistogramData,
  PhaseOneHistogramSeriesApi,
  PhaseOneHistogramSeriesOptions,
  PhaseOneLineData,
  PhaseOneLineSeriesApi,
  PhaseOneLineSeriesOptions,
  PhaseOneMainChartType,
  PhaseOneMainSeriesApi,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneMovingAverageStudyApi,
  PhaseOneMovingAverageStudyOptions,
  PhaseOneOverlaySeriesApi,
  PhaseOnePaneApi,
  PhaseOnePaneEvent,
  PhaseOnePaneEventHandler,
  PhaseOnePaneEventType,
  PhaseOnePaneKind,
  PhaseOnePaneOptions,
  PhaseOnePaneSeriesState,
  PhaseOnePaneState,
  PhaseOnePaneResizeEvent,
  PhaseOnePaneResizeHandler,
  PhaseOnePriceLineApi,
  PhaseOnePriceLineOptions,
  PhaseOnePriceScaleApi,
  PhaseOneReadoutDetail,
  PhaseOneReadoutSeriesDetail,
  PhaseOneSeriesMarker,
  PhaseOneSeriesMarkerPosition,
  PhaseOneSeriesMarkerShape,
  PhaseOneSeriesTarget,
  PhaseOneTimeScaleApi,
  PhaseOneChartTypeChangeHandler,
  PhaseOneVolumeData,
  PhaseOneVolumeSeriesApi,
  PhaseOneVolumeSeriesOptions,
  PhaseOneVolumeSeriesTarget,
};

export function getChartxFoundation(): EngineBoundarySummary {
  return getEngineBoundarySummary();
}

export function mountChartxPhaseOneHarness(canvas: HTMLCanvasElement): () => void {
  return mountPhaseOneChartHarness(canvas);
}

export function createChartxPhaseOneChart(canvas: HTMLCanvasElement): PhaseOneChartApi {
  return createPhaseOneChart(canvas);
}
