import {
  getEngineBoundarySummary,
  type EngineBoundarySummary,
} from "../internal/foundation";
import {
  inferAverageTrueRange,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
  resolveTradeLocationState,
  resolveTradeOverlayOptions,
} from "../internal/model";
import type {
  PhaseOneMainChartType,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneResolvedTradeOverlayOptions,
  PhaseOneTradeLocationRequest,
  PhaseOneTradeLocationState,
  PhaseOneTradeOverlayOptions,
} from "../internal/model";
import {
  createPhaseOneChart,
  mountPhaseOneChartHarness,
  type PhaseOneAreaSeriesApi,
  type PhaseOneAreaSeriesOptions,
  type PhaseOneBaselineSeriesApi,
  type PhaseOneBaselineSeriesOptions,
  type PhaseOneBarSeriesApi,
  type PhaseOneBarSeriesOptions,
  type PhaseOneCandlestickData,
  type PhaseOneCandlestickSeriesApi,
  type PhaseOneCandlestickSeriesOptions,
  type PhaseOneChartApi,
  type PhaseOneChartOptions,
  type PhaseOneChartStateSnapshot,
  type PhaseOneChartTemplate,
  type PhaseOneChartTemplateInput,
  type PhaseOneChartTypeChangeHandler,
  type PhaseOneClickEvent,
  type PhaseOneClickHandler,
  type PhaseOneCompareSeriesApi,
  type PhaseOneCompareSeriesOptions,
  type PhaseOneCrosshairMoveEvent,
  type PhaseOneCrosshairMoveHandler,
  type PhaseOneDrawingPropertyField,
  type PhaseOneDrawingPropertyFieldSchema,
  type PhaseOneDrawingPropertySchema,
  type PhaseOneDrawingPropertySectionSchema,
  type PhaseOneDrawingSelectionChangeHandler,
  type PhaseOneDrawingStateSnapshot,
  type PhaseOneFormattedReadoutValues,
  type PhaseOneHistogramData,
  type PhaseOneHistogramSeriesApi,
  type PhaseOneHistogramSeriesOptions,
  type PhaseOneHorizontalLineDrawingApi,
  type PhaseOneHorizontalLineDrawingOptions,
  type PhaseOneLineData,
  type PhaseOneLineSeriesApi,
  type PhaseOneLineSeriesOptions,
  type PhaseOneMainSeriesApi,
  type PhaseOneMainSeriesStateSnapshot,
  type PhaseOneMovingAverageStudyApi,
  type PhaseOneMovingAverageStudyOptions,
  type PhaseOneOverlaySeriesApi,
  type PhaseOnePaneApi,
  type PhaseOnePaneEvent,
  type PhaseOnePaneEventHandler,
  type PhaseOnePaneEventType,
  type PhaseOnePaneKind,
  type PhaseOnePaneOptions,
  type PhaseOnePaneResizeEvent,
  type PhaseOnePaneResizeHandler,
  type PhaseOnePaneSeriesState,
  type PhaseOnePaneState,
  type PhaseOnePriceLineApi,
  type PhaseOnePriceLineOptions,
  type PhaseOnePriceScaleApi,
  type PhaseOneReadoutDetail,
  type PhaseOneReadoutSeriesDetail,
  type PhaseOneSelectedDrawing,
  type PhaseOneSeriesMarker,
  type PhaseOneSeriesMarkerPosition,
  type PhaseOneSeriesMarkerShape,
  type PhaseOneSeriesTarget,
  type PhaseOneSeriesValueFormatter,
  type PhaseOneTimeScaleApi,
  type PhaseOneTrendLineDrawingApi,
  type PhaseOneTrendLineDrawingOptions,
  type PhaseOneVolumeData,
  type PhaseOneVolumeSeriesApi,
  type PhaseOneVolumeSeriesOptions,
  type PhaseOneVolumeSeriesTarget,
} from "../internal/views";

export type {
  EngineBoundarySummary,
  PhaseOneAreaSeriesApi,
  PhaseOneAreaSeriesOptions,
  PhaseOneBaselineSeriesApi,
  PhaseOneBaselineSeriesOptions,
  PhaseOneBarSeriesApi,
  PhaseOneBarSeriesOptions,
  PhaseOneCandlestickData,
  PhaseOneCandlestickSeriesApi,
  PhaseOneCandlestickSeriesOptions,
  PhaseOneChartApi,
  PhaseOneChartOptions,
  PhaseOneChartStateSnapshot,
  PhaseOneChartTemplate,
  PhaseOneChartTemplateInput,
  PhaseOneChartTypeChangeHandler,
  PhaseOneClickEvent,
  PhaseOneClickHandler,
  PhaseOneCompareSeriesApi,
  PhaseOneCompareSeriesOptions,
  PhaseOneCrosshairMoveEvent,
  PhaseOneCrosshairMoveHandler,
  PhaseOneDrawingPropertyField,
  PhaseOneDrawingPropertyFieldSchema,
  PhaseOneDrawingPropertySchema,
  PhaseOneDrawingPropertySectionSchema,
  PhaseOneDrawingSelectionChangeHandler,
  PhaseOneDrawingStateSnapshot,
  PhaseOneFormattedReadoutValues,
  PhaseOneHistogramData,
  PhaseOneHistogramSeriesApi,
  PhaseOneHistogramSeriesOptions,
  PhaseOneHorizontalLineDrawingApi,
  PhaseOneHorizontalLineDrawingOptions,
  PhaseOneLineData,
  PhaseOneLineSeriesApi,
  PhaseOneLineSeriesOptions,
  PhaseOneMainChartType,
  PhaseOneMainSeriesApi,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneResolvedTradeOverlayOptions,
  PhaseOneTradeLocationRequest,
  PhaseOneTradeLocationState,
  PhaseOneTradeOverlayOptions,
  PhaseOneMainSeriesStateSnapshot,
  PhaseOneMovingAverageStudyApi,
  PhaseOneMovingAverageStudyOptions,
  PhaseOneOverlaySeriesApi,
  PhaseOnePaneApi,
  PhaseOnePaneEvent,
  PhaseOnePaneEventHandler,
  PhaseOnePaneEventType,
  PhaseOnePaneKind,
  PhaseOnePaneOptions,
  PhaseOnePaneResizeEvent,
  PhaseOnePaneResizeHandler,
  PhaseOnePaneSeriesState,
  PhaseOnePaneState,
  PhaseOnePriceLineApi,
  PhaseOnePriceLineOptions,
  PhaseOnePriceScaleApi,
  PhaseOneReadoutDetail,
  PhaseOneReadoutSeriesDetail,
  PhaseOneSelectedDrawing,
  PhaseOneSeriesMarker,
  PhaseOneSeriesMarkerPosition,
  PhaseOneSeriesMarkerShape,
  PhaseOneSeriesTarget,
  PhaseOneSeriesValueFormatter,
  PhaseOneTimeScaleApi,
  PhaseOneTrendLineDrawingApi,
  PhaseOneTrendLineDrawingOptions,
  PhaseOneVolumeData,
  PhaseOneVolumeSeriesApi,
  PhaseOneVolumeSeriesOptions,
  PhaseOneVolumeSeriesTarget,
};

export function getChartxFoundation(): EngineBoundarySummary {
  return getEngineBoundarySummary();
}

export function mountChartxPhaseOneHarness(canvas: HTMLCanvasElement): () => void {
  return mountPhaseOneChartHarness(canvas);
}

export function createChartxPhaseOneChart(canvas: HTMLCanvasElement): PhaseOneChartApi {
  return createPhaseOneChart(canvas);
}

export {
  inferAverageTrueRange,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
  resolveTradeLocationState,
  resolveTradeOverlayOptions,
};
