import {
  getEngineBoundarySummary,
  type EngineBoundarySummary,
} from "../internal/foundation";
import {
  buildKagiData,
  buildLineBreakData,
  buildPointFigureData,
  buildRenkoData,
  inferAverageTrueRange,
  inferKagiReversalSize,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
  resolveTradeLocationState,
  resolveTradeOverlayOptions,
} from "../internal/model";
import type {
  PhaseOneMainChartType,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneResolvedTradeOverlayOptions,
  PhaseOneTradeLocationRequest,
  PhaseOneTradeLocationState,
  PhaseOneTradeOverlayOptions,
} from "../internal/model";
import {
  createCompressedPriceBasedChartBarSequence,
  createDirectionColumnPriceBasedChartBarSequence,
} from "../internal/model/chart-bar-sequence";
import { createPlotRows } from "../internal/model/series-data";
import {
  createPhaseOneChart,
  mountPhaseOneChartHarness,
} from "../internal/views/chart-entry";
import type {
  PhaseOneAreaSeriesApi,
  PhaseOneAreaSeriesOptions,
  PhaseOneBaselineSeriesApi,
  PhaseOneBaselineSeriesOptions,
  PhaseOneBarSeriesApi,
  PhaseOneBarSeriesOptions,
  PhaseOneCandlestickData,
  PhaseOneCandlestickSeriesApi,
  PhaseOneCandlestickSeriesOptions,
  PhaseOneChartApi,
  PhaseOneChartOptions,
  PhaseOneChartStateSnapshot,
  PhaseOneChartTemplate,
  PhaseOneChartTemplateInput,
  PhaseOneChartTypeChangeHandler,
  PhaseOneClickEvent,
  PhaseOneClickHandler,
  PhaseOneCompareSeriesApi,
  PhaseOneCompareSeriesOptions,
  PhaseOneCrosshairMoveEvent,
  PhaseOneCrosshairMoveHandler,
  PhaseOneDrawingPropertyField,
  PhaseOneDrawingPropertyFieldSchema,
  PhaseOneDrawingPropertySchema,
  PhaseOneDrawingPropertySectionSchema,
  PhaseOneDrawingSelectionChangeHandler,
  PhaseOneDrawingStateSnapshot,
  PhaseOneFormattedReadoutValues,
  PhaseOneHistogramData,
  PhaseOneHistogramSeriesApi,
  PhaseOneHistogramSeriesOptions,
  PhaseOneHorizontalLineDrawingApi,
  PhaseOneHorizontalLineDrawingOptions,
  PhaseOneLineData,
  PhaseOneLineSeriesApi,
  PhaseOneLineSeriesOptions,
  PhaseOneMainSeriesApi,
  PhaseOneMainSeriesStateSnapshot,
  PhaseOneMarkerGeometryHandler,
  PhaseOneMarkerGeometrySnapshot,
  PhaseOneMovingAverageStudyApi,
  PhaseOneMovingAverageStudyOptions,
  PhaseOneOverlaySeriesApi,
  PhaseOnePaneApi,
  PhaseOnePaneEvent,
  PhaseOnePaneEventHandler,
  PhaseOnePaneEventType,
  PhaseOnePaneKind,
  PhaseOnePaneOptions,
  PhaseOnePaneResizeEvent,
  PhaseOnePaneResizeHandler,
  PhaseOnePaneSeriesState,
  PhaseOnePaneState,
  PhaseOnePriceLineApi,
  PhaseOnePriceLineOptions,
  PhaseOnePriceScaleApi,
  PhaseOneReadoutDetail,
  PhaseOneReadoutSeriesDetail,
  PhaseOneSelectedDrawing,
  PhaseOneSeriesMarker,
  PhaseOneSeriesMarkerGeometry,
  PhaseOneSeriesMarkerPosition,
  PhaseOneSeriesMarkerShape,
  PhaseOneSeriesTarget,
  PhaseOneSeriesValueFormatter,
  PhaseOneTimeScaleApi,
  PhaseOneTimeFocusRequest,
  PhaseOneTimeFocusResult,
  PhaseOneTrendLineDrawingApi,
  PhaseOneTrendLineDrawingOptions,
  PhaseOneVolumeData,
  PhaseOneVolumeSeriesApi,
  PhaseOneVolumeSeriesOptions,
  PhaseOneVolumeSeriesTarget,
} from "../internal/views/chart-api-types";

export type {
  EngineBoundarySummary,
  PhaseOneAreaSeriesApi,
  PhaseOneAreaSeriesOptions,
  PhaseOneBaselineSeriesApi,
  PhaseOneBaselineSeriesOptions,
  PhaseOneBarSeriesApi,
  PhaseOneBarSeriesOptions,
  PhaseOneCandlestickData,
  PhaseOneCandlestickSeriesApi,
  PhaseOneCandlestickSeriesOptions,
  PhaseOneChartApi,
  PhaseOneChartOptions,
  PhaseOneChartStateSnapshot,
  PhaseOneChartTemplate,
  PhaseOneChartTemplateInput,
  PhaseOneChartTypeChangeHandler,
  PhaseOneClickEvent,
  PhaseOneClickHandler,
  PhaseOneCompareSeriesApi,
  PhaseOneCompareSeriesOptions,
  PhaseOneCrosshairMoveEvent,
  PhaseOneCrosshairMoveHandler,
  PhaseOneDrawingPropertyField,
  PhaseOneDrawingPropertyFieldSchema,
  PhaseOneDrawingPropertySchema,
  PhaseOneDrawingPropertySectionSchema,
  PhaseOneDrawingSelectionChangeHandler,
  PhaseOneDrawingStateSnapshot,
  PhaseOneFormattedReadoutValues,
  PhaseOneHistogramData,
  PhaseOneHistogramSeriesApi,
  PhaseOneHistogramSeriesOptions,
  PhaseOneHorizontalLineDrawingApi,
  PhaseOneHorizontalLineDrawingOptions,
  PhaseOneLineData,
  PhaseOneLineSeriesApi,
  PhaseOneLineSeriesOptions,
  PhaseOneMainChartType,
  PhaseOneMainSeriesApi,
  PhaseOneMainSeriesBuilder,
  PhaseOneMainSeriesInputCapability,
  PhaseOneMainSeriesRenderer,
  PhaseOneResolvedTradeOverlayOptions,
  PhaseOneTradeLocationRequest,
  PhaseOneTradeLocationState,
  PhaseOneTradeOverlayOptions,
  PhaseOneMainSeriesStateSnapshot,
  PhaseOneMarkerGeometryHandler,
  PhaseOneMarkerGeometrySnapshot,
  PhaseOneMovingAverageStudyApi,
  PhaseOneMovingAverageStudyOptions,
  PhaseOneOverlaySeriesApi,
  PhaseOnePaneApi,
  PhaseOnePaneEvent,
  PhaseOnePaneEventHandler,
  PhaseOnePaneEventType,
  PhaseOnePaneKind,
  PhaseOnePaneOptions,
  PhaseOnePaneResizeEvent,
  PhaseOnePaneResizeHandler,
  PhaseOnePaneSeriesState,
  PhaseOnePaneState,
  PhaseOnePriceLineApi,
  PhaseOnePriceLineOptions,
  PhaseOnePriceScaleApi,
  PhaseOneReadoutDetail,
  PhaseOneReadoutSeriesDetail,
  PhaseOneSelectedDrawing,
  PhaseOneSeriesMarker,
  PhaseOneSeriesMarkerGeometry,
  PhaseOneSeriesMarkerPosition,
  PhaseOneSeriesMarkerShape,
  PhaseOneSeriesTarget,
  PhaseOneSeriesValueFormatter,
  PhaseOneTimeScaleApi,
  PhaseOneTimeFocusRequest,
  PhaseOneTimeFocusResult,
  PhaseOneTrendLineDrawingApi,
  PhaseOneTrendLineDrawingOptions,
  PhaseOneVolumeData,
  PhaseOneVolumeSeriesApi,
  PhaseOneVolumeSeriesOptions,
  PhaseOneVolumeSeriesTarget,
};

export function getChartxFoundation(): EngineBoundarySummary {
  return getEngineBoundarySummary();
}

export function mountChartxPhaseOneHarness(canvas: HTMLCanvasElement): () => void {
  return mountPhaseOneChartHarness(canvas);
}

export function createChartxPhaseOneChart(canvas: HTMLCanvasElement): PhaseOneChartApi {
  return createPhaseOneChart(canvas);
}

export {
  buildKagiData,
  buildLineBreakData,
  buildPointFigureData,
  buildRenkoData,
  createCompressedPriceBasedChartBarSequence,
  createDirectionColumnPriceBasedChartBarSequence,
  createPlotRows,
  inferAverageTrueRange,
  inferKagiReversalSize,
  inferPercentageBoxSize,
  inferPointFigureBoxSize,
  inferTraditionalPointFigureBoxSize,
  resolveTradeLocationState,
  resolveTradeOverlayOptions,
};
